# Generated by Django 5.1 on 2024-08-18 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='mime',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clip',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='clip',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
