# Generated by Django 5.1 on 2024-08-18 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0002_clip_mime_clip_text_alter_clip_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
